### ISSUE TITLE
Multi-level settings?

### ISSUE THREAD

**Issue by tralston** [railsware/global#3]
I'd love to be able to do this:
(in config/global/filename.rb)

```
default:
  group1:
    action: delete
    method: something
  group2:
    action: save
    method: something_else
```

and access them with

```
Global.filename.group1.action
```

All I get right now a NoMethodError, because the gem only returns the first level (under the environment):

```
Global.filename.group1
# => { "action" => "delete", "method" => "something" }
```

Is there a way to access nested settings without overriding method_missing? or extending the Hash class?
