### ISSUE TITLE
default section should not be evaluated if it is being overridden in other environments

### ISSUE THREAD

**Issue by ddi-wtag** [railsware/global#31]
## Background

```yaml
# config/settings/service.yml
default:
  url: <%= ENV.fetch('SERVICE_URL') %>

development:
  url: service.dev
production:
```

### Development

```ruby
irb(main):001:0> Global.service.url
=> "service.dev"
```

### production

Works fine as long as we have defined the `SERVICE_URL` environment variable.

### Development

```ruby
irb(main):001:0> Global.service.url
Traceback (most recent call last):
        3: from (irb):1
        2: from (erb):3:in `<main>'
        1: from (erb):3:in `fetch'
KeyError (key not found: "SERVICE_URL")
```

### Production

Works fine as long as we have defined the `SERVICE_URL` environment variable.

**Comment by le0pard** [comment]
Hello @ddi-wtag What will be expectation, if we have different keys in `default` and environment key. Example:

```yaml
default:
  some_key: value

development:
  another_key: different value
```

**Comment by ddi-wtag** [comment]
@le0pard 

I would expect both keys to be present if they are different, so in your example, I would say the following:

### Development

`Global.service.somekey` would return `value`, and `Global.service.another_key` would return `different value`.

### Any other environment

`Global.service.somekey` would return `value`, and `Global.service.another_key` would not be available.

**Comment by le0pard** [comment]
Thanks @ddi-wtag 

So as you can see, system still need to do evaluation for `default` section to make merge of a keys. In codebase it works in this way:

default keys <- override by env keys

Also, we support yaml files like erb templates, so you can write `for/if/etc` in it. But to parse yaml we have to apply erb to content. What is why any ruby code will be executed in this files before merging of the keys.

In your case best way to solve problem:

```yaml
# config/settings/service.yml
default:
  url: <%= ENV.fetch('SERVICE_URL', nil) %>

development:
  url: service.dev
production:
  url: <%= ENV.fetch('SERVICE_URL') %>
```
