### ISSUE TITLE
documentation is too cryptic.

### ISSUE THREAD

**Issue by airtonix** [railsware/global#38]
I tried using this library verbatim from the README.md but i keep getting errors like: 

- missing key path, or
- undefined method 'application'

It's not clear if i can point at a single file:

```yml
# ./packages/fastlane/defaults.yml
---
defaults:
  application:
    name: Test
```

```ruby
# ./packages/fastlane/Fastlane

fastlane_require 'global'


Global.configure do |config|
  config.backend :filesystem, path: './defaults.yml', environment: 'development'
end

puts(Global.application.name)
```
error: 
```
<PROJECT_ROOT>/vendor/bundle/ruby/2.4.0/gems/global-2.0.0/lib/global/base.rb:62:in `method_missing': [!] undefined method `application' for Global:Module (NoMethodError)

etc
etc
etc
```

So yeah. documentation is um. misleading?
