### ISSUE TITLE
Undefined method "myvar" for Global:Module (NoMethodError)

### ISSUE THREAD

**Issue by NosherwanA** [railsware/global#42]
## Description:
I am trying to use this library for configuration management in a basic Ruby script. However, I am running into NoMethodError everytime I try to access anything. It's not clear what is missing. I have the following setup:

## Directory Structure:
![Directory Structure](https://user-images.githubusercontent.com/23142798/179004444-35d8b298-c97b-4a44-9fa3-900965e1b1ab.png)

## Files:
```
#main/main.rb
#!/tool/pandora64/.package/ruby-2.7.1/bin/ruby -W0
require "global"


Global.configure do |config|
    config.backend :filesystem, path: '../config', environment: 'development'
end

print "Global.myvar = #{Global.myvar}"
```

```
#config/class1_config.yml
#class1_config
development:
  myvar: 2
  line_num: 5
  test_str: my string
production:
  myvar: 100
  line_num: 20
  email_list:
    from: service_account
    to:
      - user1
      - user2
```

## Console Log:
```
[nosahmed@atletx7-reg071: ~/config_test]$  main/main.rb
Traceback (most recent call last):
        1: from main/main.rb:9:in `<main>'
/tool/pandora64/.package/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/global-2.1.0/lib/global/base.rb:62:in `method_missing': undefined method `myvar' for Global:Module (NoMethodError)
```

## Versions:

- Ruby : 2.7.1
- Global: 2.1.0
